### ISSUE TITLE
Zone matrix incorrect download

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#109]
Fixed by adding it to eeprom download batch instead, and then interpret the data.
6h.

**Comment by borisbergman** [comment]
Ensure all routing/checkmarks are properly set during upload and after download these are equal!

**Comment by RamonZwaga** [comment]
Ensure all routing/checkmarks are properly set during upload and that after a download these are equal!
Now in some GUI versions the matrix is empty, or some fields are empty:

![image](https://cloud.githubusercontent.com/assets/8523943/23361421/e2cb8f28-fcf0-11e6-922b-c03fc631ac9a.png)

**Comment by hoherprotektor** [comment]
![grafik](https://cloud.githubusercontent.com/assets/19922934/23506302/da2d0168-ff47-11e6-80f2-f0c8cfe8dc26.png)

When you upload this config this one appears after refreshing, but after download everthing is ok.

![grafik](https://cloud.githubusercontent.com/assets/19922934/23506341/188278bc-ff48-11e6-9f42-e272a836d42e.png)

**Comment by borisbergman** [comment]
Done

**Comment by hoherprotektor** [comment]
upload or downlaod is not working anymore. When we uplaod a new design and download it afterwards the changes are not in. Also when we download an empty design after factory reset the standart routing is not shown, so it seems that the download is not working anymore

**Comment by RamonZwaga** [comment]
so when we do a download from a new unit, the matrix is empty!

**Comment by borisbergman** [comment]
I broke something in the communication part. I'll go ahead and fix it.

**Comment by hoherprotektor** [comment]
uploadload and download seems to work. 
but the refreshing still behalf like in the second picture. when downloading it seems ok.

**Comment by hoherprotektor** [comment]
Upload:
![upload](https://cloud.githubusercontent.com/assets/19922934/25228182/ba98d3cc-25cb-11e7-9775-a57dd3287d12.JPG)
Refresh:
![refresh](https://cloud.githubusercontent.com/assets/19922934/25228204/d09e3c48-25cb-11e7-812d-996cb9b946fa.JPG)
Download:
![download](https://cloud.githubusercontent.com/assets/19922934/25228216/dea3a5e4-25cb-11e7-965c-3c7274759216.JPG)

**Comment by hoherprotektor** [comment]
When doing this for all outputs it is refreshed ok
![ok](https://cloud.githubusercontent.com/assets/19922934/25228339/5a066758-25cc-11e7-9731-e23034d047c6.JPG)

**Comment by borisbergman** [comment]
What does "refresh" mean?

**Comment by hoherprotektor** [comment]
refresh like on the second picture. please test it with an eXentro then you can see it directly.
After uploading a routing it is shown wrong(row and columns are changed). Its not fixed yet.

**Comment by borisbergman** [comment]
Whooops, made a mistake, sorry about that. Fixed.
