### ISSUE TITLE
Not enough biquads available message

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#113]
EQ laden in de AUX PEQ – men weet dat b.v. de EQ van de DS16 maar 7 banden heeft, toch kun je deze niet laden in de AUX. Dit komt omdat er een 4e order BW filter inzit en je dus eigenlijk 8 filters wilt laden. Dus de popup moet aangeven: “The chosen speaker EQ requires 8 filters (possibly due to a 4th order High or Low cut off, requiring 2 filters); the EQ has space for 7 filters max. Change EQ parameters and save as a custom EQ in the library; select this new EQ to upload.’

Overigens bij versie 9.14 heb ik ook geprobeerd die DS16 te laden in een AUX en dan staat wel all de naam weergegeven, maar geen filters vanwege die space. Als je dan de module weer sluit blijft die ‘DS16’ –naam als gekozen filter in de module staan, zie 2e plaatje hieronder met een MA12 EQ (wekle ook niet past in 7 filters)

**Comment by RamonZwaga** [comment]
popup message Is now correct for a filter like the DS16, but when selecting the M32 (having 5 bands) the same message is displayed. Does the filter count function properly? Seems partly finished, is 8 hrs. still needed?

**Comment by borisbergman** [comment]
The m32 actually does fit in the auxiliary peq without any messages. Either it is solved or the issue is described incorrectly.
