### ISSUE TITLE
Speakermatrix module apperance

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#123]
![loudspeakermatrix](https://cloud.githubusercontent.com/assets/6067502/6272436/dd46c8e4-b867-11e4-803f-bb9d1a88934f.jpg)

**Comment by RamonZwaga** [comment]
![image](https://cloud.githubusercontent.com/assets/8523943/11120363/48e64706-894f-11e5-8602-0a10dbcbbef9.png)

de klikfunctie op die matrix weglaten, zodat het scherm onderaan ook niet die opkomt.
