### ISSUE TITLE
Get deviation, impedance and frequency value from esc

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#125]

**Comment by RamonZwaga** [comment]
see also # 126 for low impedance or 100V line.
Note: if no data is received yet from ESC: default frequency is 22khz and deviation is

**Comment by RamonZwaga** [comment]
die info krijg je vanuit de ESC, zie protocol

**Comment by borisbergman** [comment]
Scoop creep. clarify? What radio where?

**Comment by RamonZwaga** [comment]
![image](https://cloud.githubusercontent.com/assets/8523943/11443874/0afd6bda-9521-11e5-9efc-faa04b82942c.png)

dit zijn de default instellingen.
wanneer de esc is gekalibreerd krijg je via de install tree mogelijk andere instellingen.

Vwb de loads; bij een M&S configuratie, na download, dan laat de Master wel load waardes zien, maar bij de slave staan ze niet.

**Comment by borisbergman** [comment]
kan je een esc file posten waarbij dit van toepassing is? Wanneer kies ik voor de default waarde?

**Comment by RamonZwaga** [comment]
deafult is bij openen nieuw design, pas wanneer je een download hebt gedaan, dan haal je de in de ESC gekozen deviation instellingen op, et als die 100V/Low impedance en de monitoring frequency

**Comment by RamonZwaga** [comment]
[fc-utrecht_V2.zip](https://github.com/borisbergman/EscInstaller/files/68521/fc-utrecht_V2.zip)

Als je dit design opent en dan naar b.v. Master kanaal 7 van monitoring gaat, dan zie je bij de 1kHz lijn B 10.000 ohm staan, terwijl er geen belasting aan lijn B hangt.

In dit utrecht design kun je ook zien dat bij de slaves geen getallen in de monitoring modules staat...
vreemd, want de namen e.d worden wel weergegeven. Is ook geen refresh issue....

Vwb laagohmig: wanneer je in het design ziet dat een uitgang laagohmig is, dan de velden welke Watt (W) aangeven greyed out maken; in geval van laagohmig moet alleen het vakje voor ohm ingevuld worden. Die 'ohm' berekeningen maak je hier toch aan de hand van het 'wattage' welke je van de ESC krijgt? Dus wanneer je b.v 500W krijgt, dan reken jij dit om naar 20 ohm toch? Zoja: in het geval van laagohmig (krijg je ook uit de esc), krijg je b.v. 1200W van de ESC: doe je 10000/1200W = 8 ohm en wetende (vanuit de esc) dat het om laagohmig gaat, laat je alleen die '8 ohm' zien, niet die 1200W. SNAP JE M? Of haal je de 'measurement values' uit de eprom (zoals ik net in protocol las)? In dat geval zou je die info ook moeten kunnen zien/omrekenen.

**Comment by borisbergman** [comment]
Kan je die mee sturen, dat design uit utrecht?
    Met vriendelijke groet,


Boris Bergman
    On 12/21/2015 3:14 PM, RamonZwaga
      wrote:
    
    
      fc-utrecht_V2.zip
      Als je dit design opent en dan naar b.v. Master kanaal 7 van
        monitoring gaat, dan zie je bij de 1kHz lijn B 10.000 ohm staan,
        terwijl er geen belasting aan lijn B hangt.
      In dit utrecht design kun je ook zien dat bij de slaves geen
        getallen in de monitoring modules staat...
        vreemd, want de namen e.d worden wel weergegeven. Is ook geen
        refresh issue....
      Vwb laagohmig: wanneer je in het design ziet dat een uitgang
        laagohmig is, dan de velden welke Watt (W) aangeven greyed out
        maken; in geval van laagohmig moet alleen het vakje voor ohm
        ingevuld worden. Die 'ohm' berekeningen maak je hier toch aan de
        hand van het 'wattage' welke je van de ESC krijgt? Dus wanneer
        je b.v 500W krijgt, dan reken jij dit om naar 20 ohm toch? Zoja:
        in het geval van laagohmig (krijg je ook uit de esc), krijg je
        b.v. 1200W van de ESC: doe je 10000/1200W = 8 ohm en wetende
        (vanuit de esc) dat het om laagohmig gaat, laat je alleen die '8
        ohm' zien, niet die 1200W. SNAP JE M? Of haal je de 'measurement
        values' uit de eprom (zoals ik net in protocol las)? In dat
        geval zou je die info ook moeten kunnen zien/omrekenen.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by borisbergman** [comment]
set to 30%

**Comment by RamonZwaga** [comment]
fields are now 'greyed-out': do we need these back? To be able to indicate a low impedance line, the data must be retrieved from ECU, so only the impedance is displayed and the load in W is not displayed (in low impedance mode)

**Comment by hoherprotektor** [comment]
Protocol point exists 
![grafik](https://cloud.githubusercontent.com/assets/19922934/24741632/14518b3c-1aa7-11e7-80f8-0502ec90f394.png)

**Comment by borisbergman** [comment]
Done. Not sure if loads are downloaded correctly, please check.

**Comment by RamonZwaga** [comment]
Is partly not operating correct; comments will follow!

**Comment by RamonZwaga** [comment]
![image](https://cloud.githubusercontent.com/assets/8523943/26297044/9192c540-3ed1-11e7-8188-a181dfba7438.png)

1. Deviation fields are wrongly located in window! (crossed)
2. Selected deviation (position) does not match selection in ECU (see protocol); values are OK.; Michael what is the default deviation value?
3. Monitoring settings, do not match the selected option as in the ECU (see also item #126: when a low impedance line was calibrated)
4. Monitoring frequency not correct! Was still at default in ECU, bit installer shows 19kHz; Michael which is the default value?

**Comment by hoherprotektor** [comment]
static const INT16U u16_deviation_1khz_percent_tab[C_KREIS_CHECK_LIMITS_SENSITIVITIES] =
       {
       5, 10, 20, 30, 50, // deviation in percent of installed power 
       };

static const INT16U u16_deviation_20khz_percent_tab[C_KREIS_CHECK_LIMITS_SENSITIVITIES] =
       {
       5, 10, 20, 30, 50, // deviation in percent of installed power 
       };


20 is standard

**Comment by hoherprotektor** [comment]
[Boris.zip](https://github.com/borisbergman/EscInstaller/files/1128249/Boris.zip)

**Comment by RamonZwaga** [comment]
![image](https://user-images.githubusercontent.com/8523943/34080925-f68a754c-e345-11e7-9a64-b93862f92144.png)
It seems the default piolt frequency is ok now, but is the default deviation also ok?

Michael 1 more time to confirm: default Dev. is 20% and Default Freq. is 20kHz?

**Comment by RamonZwaga** [comment]
And Michael, for low impedance?:
![image](https://user-images.githubusercontent.com/8523943/34080948-3b96ecf6-e346-11e7-8965-fcef45ce880a.png)

If GUI gets/reads the Low-imp. settings from the EEProm data (as in picture: how does the deviation look like? Still the same 5 options?

**Comment by borisbergman** [comment]
I'll wait till you guys made up your mind.

**Comment by RamonZwaga** [comment]
If #126 is fixed, this issue can be closed also

**Comment by mrgplusm** [comment]
standard- values are for deviation: 20%; impedance: 20kHz

**Comment by RamonZwaga** [comment]
Issue closed, new issue #231 opened for 'Default settings'
