### ISSUE TITLE
Remove all backup amps that are not installed from schematic

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#130]

**Comment by borisbergman** [comment]
Cannot find documentation.

**Comment by RamonZwaga** [comment]
deze hoort bij #192, maar behoeft verder geen actie meer als #192 goed werkt

**Comment by RamonZwaga** [comment]
staat op fixed omdat #192 deze vervangt

**Comment by borisbergman** [comment]
In principe is er geen fixed label nodig. Gesloten issues worden niet meer gedaan/zijn al gedaan.
