### ISSUE TITLE
Slave has no load values

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#142]

**Comment by RamonZwaga** [comment]
als je een design hebt geladen (met calibratie datea erin), dan zie je de loads wel voor de master, maar niet voor de slave esc's

**Comment by RamonZwaga** [comment]
![image](https://cloud.githubusercontent.com/assets/8523943/11304370/07846c16-8fa8-11e5-9237-d22ad4bca92a.png)

dit is van fc utrecht de master unit; deze geeft wel de loads aan

![image](https://cloud.githubusercontent.com/assets/8523943/11304391/21fdcf1a-8fa8-11e5-9061-55b89b2775e8.png)

dit is dan de slave unit, waar geen loads ed in staan

daarnaast is de selectie voor deviation en pilot-freq niet goed, zie ook #125

**Comment by RamonZwaga** [comment]
loads staan nu wel in de slave onder de monitoring knop, maar op je scherm zie je achter de speaker icons nog geen Wattage weergegeven.....

**Comment by borisbergman** [comment]
jawel, de 1khz wattage
