### ISSUE TITLE
Pre-announcement 255 (FF)

### ISSUE THREAD

**Issue by AFJreus** [borisbergman/EscInstaller#156]
After a factor reset the value of the Pre-announcements is FF (just like the ABCD messages)
But in the installer software position 255 is selected for the pre-announcements. but must be "no message"

**Comment by borisbergman** [comment]
The installer selects 255 when 254 is send by the esc. Please supply truth table.

**Comment by AFJreus** [comment]
In the past this was already discussed. eprom default value is FF (empty location).
So if value is FF then "No Message"

**Comment by borisbergman** [comment]
If you close the issue, it won't be solved :)
if already discussed, please paste the results in here.

**Comment by AFJreus** [comment]
So if value is FF then "No Message"

**Comment by borisbergman** [comment]
duplicate #157
