### ISSUE TITLE
Message selection issue

### ISSUE THREAD

**Issue by AFJreus** [borisbergman/EscInstaller#157]
When downloading from a factory restored ESC, Button A of the FP is programmed as 3th message.
should be "Matrix"

**Comment by borisbergman** [comment]
Does this happen every time you try? Did you check what data is coming out of the esc?

**Comment by AFJreus** [comment]
Thought so yes.
Come to the office so you can test it yourself with a "real" ESC ;-)

**Comment by borisbergman** [comment]
Please don't close issues before fixing them!
Please paste the array the esc replays on getmessageselection command:

 {[0x81,0x01,0x0B,0x10,0x06,0x00,0x00,0xA4,0x00,0x1E,0x65]}

**Comment by AFJreus** [comment]
After factory restore:
Send: 81 01 0B 10 06 00 00 A4 00 1E 65

Received: 01 81 24 12 0E 01 02 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 00 AE

**Comment by borisbergman** [comment]
Wrote email to Phillipe and Michael:

So I'll interpret this as 0x01 == first message, message 1.
Please tell us, what number (hex) do I send to get the following:

- Message 1 
- Message 2
- No message/Matrix selection
- Message 254
- Message 255 (should be 256 options right?)

When I receive a byte array of the esc:
- What does 0x00 (the last byte before checksum meant for external audio) mean?
- Can I interpret 0xFF being no message?
- Is 0x01 message 1 and 0x02 message 2?

**Comment by borisbergman** [comment]
Issue still open. When choosing any kind of selection and send it to the esc, the feedbackdata (downloading the messages) is just random.

**Comment by borisbergman** [comment]
Idea Ramon: Add selection to redundancy data instead of retrieving from current location.

**Comment by borisbergman** [comment]
Preannouncements: no message is interpreted as 255.
