### ISSUE TITLE
Connection warning message

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#160]
A predefined connection message should show instead of the default error call stack.

**Comment by RamonZwaga** [comment]
![image](https://cloud.githubusercontent.com/assets/8523943/23356803/7eb6560e-fcdb-11e6-9c0a-361c9217bd1f.png)

**Comment by borisbergman** [comment]
Only change of text: "No Connection or No Connection established"

**Comment by hoherprotektor** [comment]
Please change to this because No Connection or no Connection established means the same.  "No cable connection or ne connection established".
