### ISSUE TITLE
ABCD button constraint

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#171]
ABCD buttons: Using alarm2 selection only possible if at least one of the 12 other outputs has alarm1 selected

**Comment by RamonZwaga** [comment]
Je kunt pas in de kolom van 'alarm 2' een keuze maken als er minimaal 1 selectie is gemaakt bij de kolom 'alarm 1'

**Comment by borisbergman** [comment]
I know,  dit bracht nogal wat verandering teweeg. 


Sent from my Samsung device

-------- Original message --------

**Comment by borisbergman** [comment]
implications:
- count all alarm1 messages, if none, disable alarm2
  * do not count those messages of cards not installed
- disable "select all alarm2" as this can never happen 
- disable alarm2 of selected alarm1 message when no other alarm1 is selected. 
- remove all alarm2 selections when alarm1 count < 0
- update whole columns after each alarm1 selection change
