### ISSUE TITLE
peq aux label incorrect text downloaded

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#177]

**Comment by RamonZwaga** [comment]
text is correct but requires a tab refresh to indicate the name of chosen filter

**Comment by borisbergman** [comment]
wat bedoel je precies?

**Comment by RamonZwaga** [comment]
zoals het er staat:
na kiezen moet er blijkbaar eerst een refresh plaatsvinden, dan pas zie je juiste selectie

**Comment by RamonZwaga** [comment]
Is ok in V13.8.2; re-check this 'refresh' issue in next releases; also because there are other 'refresh issues': so after a code change, make sure this stays ok.

**Comment by borisbergman** [comment]
Please describe issue appropriately. What exactly happens with the AUX PEQ text?

**Comment by RamonZwaga** [comment]
Clarification: if for the AUX an EQ was selected from the library, the name of this EQ was not directly visible. So a refresh had to take place (e.g. go to 'matix tab' and go back again) before it was displayed.

**Comment by borisbergman** [comment]
That's currently not the case. The name is immediately visible after choosing a library speaker.
