### ISSUE TITLE
Saved connections are not checked against open ones for equality

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#188]

**Comment by RamonZwaga** [comment]
wat bedoel je hier mee, we snappen het issue niet

**Comment by borisbergman** [comment]
Deze werktaak was al gesloten op 12 oktober. Het probleem is dat er in het ontwerp bestand verbindingen naar de esc opgeslagen worden. (poort/ip adres)
Er kan ook een design geopend worden terwijl er al verbindingen open staan. Er moet dus gekeken worden of de verbindingen in het design overeenkomen met de verbindingen die open staan om te voorkomen dezelfde verbinding meermaals weergegeven wordt.

**Comment by RamonZwaga** [comment]
ok duidelijk
