### ISSUE TITLE
After design download: 2 Master tabs appear AND refresh issue: data not shown

### ISSUE THREAD

**Issue by RamonZwaga** [borisbergman/EscInstaller#199]
it is not possible to remove the 2nd Master tab from the design

design not refreshed: save design and re-open DOES show correct settings AND the 2nd Master dissapeared

**Comment by RamonZwaga** [comment]
after adding a slave connection, we also get double slave, also in matrix, see with pict from Arno

**Comment by RamonZwaga** [comment]
![image](https://cloud.githubusercontent.com/assets/8523943/11717386/8878625c-9f50-11e5-95ac-c3f029253c91.png)
![image](https://cloud.githubusercontent.com/assets/8523943/11717396/8da37ce4-9f50-11e5-9f2c-9b0cf0cef8af.png)

**Comment by borisbergman** [comment]
RZ: When I connect to a master and download the design, there are two master tabs in the software. Same when 1 or more Slave devices are in the system!

Number of 4x4 cards is also not refreshed correctly: it first shows 1 card and after clicking ‘zone matrix’ and back to ‘Master’ tab, you will get the actual nr. Of cards installed

**Comment by RamonZwaga** [comment]
This issue seems to be back, was solved in SW version from March 2016

**Comment by borisbergman** [comment]
Done

**Comment by borisbergman** [comment]
Fixed
