### ISSUE TITLE
Data ESC Mismatch does not show the ESC units from which to download

### ISSUE THREAD

**Issue by RamonZwaga** [borisbergman/EscInstaller#200]
popup geeft 2 streepjes aan (blijkbaar voor de 2 units), dit weghalen?

**Comment by borisbergman** [comment]
fixed

**Comment by RamonZwaga** [comment]
![image](https://cloud.githubusercontent.com/assets/8523943/11717338/4352d02c-9f50-11e5-9e94-4e8db4cc5627.png)

was dat deze?

**Comment by RamonZwaga** [comment]
Ja of nee?

**Comment by borisbergman** [comment]
de esc units staan op de plek van -
