### ISSUE TITLE
Display of installed power in W if 0 display '-'

### ISSUE THREAD

**Issue by RamonZwaga** [borisbergman/EscInstaller#201]
als belasting 0W is (ofwel lager dan 10W), dan niet 0 laten zien maar '-'; dit ook doen voor de 'impedantie (ohm) daaronder '-' aangeven en niet 0 ohm (dat is een kortsluiting)

**Comment by borisbergman** [comment]
bij de speaker is dit kleiner dan 10, ik gebruik nu ook < 10 voor monitoring

**Comment by RamonZwaga** [comment]
![image](https://cloud.githubusercontent.com/assets/8523943/11717364/64ffee6c-9f50-11e5-85be-24136e095bfa.png)

prima, alleen 0 ohm kan niet, dat is een korstluiting, dus dan een '-' plaatsen

**Comment by RamonZwaga** [comment]
is deze nu gefixed?

**Comment by borisbergman** [comment]
Ja, ik hoop het wel

**Comment by borisbergman** [comment]
impedance is 5000 when no power found

**Comment by borisbergman** [comment]
Don't display power in watt when line is in low impedance

**Comment by RamonZwaga** [comment]
Decide with Michael which lowest value (i recall 10W) will be 'installed' by the ECU.
If value is below that, display '-', also related to item 126

**Comment by borisbergman** [comment]
Already in there.
