### ISSUE TITLE
Selected 'element' window not open anymore when toggle was performed to other tab

### ISSUE THREAD

**Issue by RamonZwaga** [borisbergman/EscInstaller#202]
1: select output 3
2: switch to matrix tab
3: switch back to Master tab > the output 3 is still indicated as selected element, but the window at the bottom is now partly visible > select another element (e.g. output 4), than output 3 again to show output 3 settings,

**Comment by borisbergman** [comment]
hard to solve. Can't find a solution now

**Comment by RamonZwaga** [comment]
![image](https://cloud.githubusercontent.com/assets/8523943/11717326/2ffaff22-9f50-11e5-8211-afa7248fd2ee.png)

dit is wat je dan ziet
