### ISSUE TITLE
'recent projects' only for 'saved' designs, not for 'save as' design

### ISSUE THREAD

**Issue by RamonZwaga** [borisbergman/EscInstaller#203]
alleen designs welke via 'save' (dus aflsuiten GUI) zijn opgeslagen komen in de lijst voor. doe je een save as dan komen die niet in dit overzicht

**Comment by borisbergman** [comment]
scoop creep.

**Comment by RamonZwaga** [comment]
wat is scoop creep....
werkt het met beide of niet? waarom anders een recent project overzicht als niet alle opgeslagen designs zichtbaar zijn...

**Comment by borisbergman** [comment]
Nee, de hele recent files is al een niche, laten we nou geen onderscheid gaan maken hoe de file ge-saved is.

**Comment by RamonZwaga** [comment]
we willen juist geen onderscheid, maar nu zie je alleen de design welke worden opgeslagen door de SW af te sluiten. Met de knop save as komen ze niet terug.... snap je m?
Maar laat deze maar zitten is niet belangrijk
