### ISSUE TITLE
IP address is not saved in design file

### ISSUE THREAD

**Issue by RamonZwaga** [borisbergman/EscInstaller#204]
after connecting to an esc, download design and save > open design in monitoring, the IP addresses are not shown!!!

**Comment by borisbergman** [comment]
why would this be necessarily?

**Comment by RamonZwaga** [comment]
je maakt de ESC configuratie via installer en Eth connectie.
wanneer config klaar is, dan open je dat design in de monitorig sw.
Die heeft dan meteen al de IP adressen waarmee je daarvoor de config via installer hebt gemaakt

dacht dat we dit zo besproken hadden

**Comment by borisbergman** [comment]
Getest en het werkt al zo, probeer het nog een keer met de laatste versie
