### ISSUE TITLE
Input output numbering disapeared?

### ISSUE THREAD

**Issue by RamonZwaga** [borisbergman/EscInstaller#206]
![image](https://cloud.githubusercontent.com/assets/8523943/11717443/dad721be-9f50-11e5-90fe-901cd43db94c.png)

voorheen zagen we daar ook het nummer van de gekozen input of output

bij de PEQ staat het nog wel:
![image](https://cloud.githubusercontent.com/assets/8523943/11717461/ee47be02-9f50-11e5-8730-2827d0ba1786.png)

**Comment by borisbergman** [comment]
done for Line monitoring, tonecontrol, inputname, outputname
