### ISSUE TITLE
peq library file disapeared

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#208]

**Comment by borisbergman** [comment]
oops solved

**Comment by borisbergman** [comment]
check again

**Comment by borisbergman** [comment]
Installation package does not include this file. Make sure it does.

**Comment by RamonZwaga** [comment]
Was already fixed for V13.8.2.: tested and seems ok. Also created Custom EQ, which was visible after closing/opening SW and creating a new file. Also opened older SW version (9.14) and the custom EQ was visible. No need for further changes? Just ensure/double check that after install of the SW, the library is located on drive correctly and when a new SW version is released, it must still be present.

**Comment by borisbergman** [comment]
This should be solved when a installation package is created, and a peq file is copied to the appropriate folder.
