### ISSUE TITLE
peq file crashes when import

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#209]
selecting speaker/import seq/peq crashes application

**Comment by borisbergman** [comment]
Cannot reproduce. Please include a test file/steps to reproduce

**Comment by hoherprotektor** [comment]
hi Boris I talked to Ramon. He said that the Installer brakes when you inserted an corrupt PEQ file. Possible you can mess up a file and then try to prevent the software from chrashing?

**Comment by hoherprotektor** [comment]
This is the case when trying to enter a broken peq file. Handling this should be done properly.

**Comment by borisbergman** [comment]
Corrupted file doesn't crash software. If any file does so, please add it to this thread
