### ISSUE TITLE
Design alterations communication window

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#211]
Change text ‘download’ in red background to ‘upload’ when uploading

**Comment by RamonZwaga** [comment]
![image](https://cloud.githubusercontent.com/assets/8523943/23356250/6db415be-fcd9-11e6-91e6-d6053433fcbc.png)

**Comment by hoherprotektor** [comment]
There are serveral issues:
1. When you press the Downlaod button and the upload button the specific window should open. At the moment only the Downloadwindow opens. The Option to toggle between the windows is not necessary. 
2. The windowname should be Download or Upload. 
3. top Progressbar is not working.
4. The Window should open that you can see the possitions for example the master should be unfolded.
5. For the left Button only start and reset is necessary. Sometimes it didn't start when you press start. Only after the second time

![gui1](https://cloud.githubusercontent.com/assets/19922934/24491087/df826ea2-1525-11e7-9d32-746f4e19fbc4.png)

**Comment by borisbergman** [comment]
For slaves keep everything folded. Remove upload toggle button, remove cancel button-> make reset take over cancel functionality. Keep parametric eq sub settings folded.

**Comment by hoherprotektor** [comment]
for uploading data. the window opens with reset but it should open with the start- button
![uloadstrartswith reset](https://cloud.githubusercontent.com/assets/19922934/25223199/000fef78-25bb-11e7-884d-d69cd605b34b.JPG)

**Comment by hoherprotektor** [comment]
also when you start uploading some uploads are at the same time. this causes problems to the EQs. Because after finish this upload the blob audio is back on the audiooutputs. It was the same when 2 Masters are uploaded at the same time.
![uploadnotseriel](https://cloud.githubusercontent.com/assets/19922934/25223314/56df0b4a-25bb-11e7-9b0f-65ef06e8bf46.JPG)

**Comment by borisbergman** [comment]
We have wait until further investigation has been done.

**Comment by hoherprotektor** [comment]
But still starting to change sequenz the order. No uplaods in parallel.

**Comment by borisbergman** [comment]
There's no proof this is causing the trouble, as discussed, nothing happens in parallel, and the DSP doesn't care what settings are uploaded first. Changing this behaviour is time consuming.

**Comment by RamonZwaga** [comment]
after opening de up/download window the button for 'start/reset' not always comes up with 'start', sometimes it first shows 'reset' > should always be 'start' when opening window!

**Comment by RamonZwaga** [comment]
what has changed to the up/download of EQ data? (in GUI or FW?) In the past we did not have this; EQ changes never gave plops in audio signal.
@ Michael; it seems we also have such issue now when the wall controller is connected!!

**Comment by borisbergman** [comment]
The past present and future are not important in this topic. The definitions of the protocol should met. If it doesn't, then I'll adjust, otherwise this topic can be closed.

**Comment by RamonZwaga** [comment]
PP&F is important: on both sides (Installer and FW) changes have been made and now we have unacceptable plopping audio sounds, so we must find out what causes this; i don't care where it goes wrong as long as it is solved.

**Comment by borisbergman** [comment]
**1** The business proposal we agreed upon only affects the pc software package, and there's a clearly defined protocol I stick to. We also agreed upon G+M would perform integration tests.
**2** Presumably we'll never find out what changed since plopping occurs, except for the case when pc software is not following protocol criteria. 
**3** The protocol never mentioned a particular order. So even when the previous version of the software works and the current does not, this does not directly imply erroneous behaviour of the pc software.

For the above reasons, I'll remove my name from the assignees list. If point 2 clearly is not met, I'll be happy to solve that particular and by then well described issue.

**Comment by hoherprotektor** [comment]
seems ok. We will see if everthing is ok. when i wrote a fix to firmware. Probably in future recognize that something is wrong with the data.

**Comment by hoherprotektor** [comment]
This problem comes up again:
after opening de up/download window the button for 'start/reset' not always comes up with 'start', sometimes it first shows 'reset' > should always be 'start' when opening window!
After downloading the data and press the button for uplaod the window opens this way.
![image](https://user-images.githubusercontent.com/19922934/33548459-82a3df64-d8e7-11e7-87d7-0f05dc13bf10.png)

**Comment by RamonZwaga** [comment]
Why not individual 'start' and 'stop' buttons? 
Is 'reset' to reset the selection?
It is confusing and it does not always start with the correct status.

**Comment by RamonZwaga** [comment]
Boris, will you change this toggle button to 2 buttons: start & stop? (then we also have no issue which the status of this button when the up/download window is opened

**Comment by borisbergman** [comment]
The button name now is properly reset when window has been closed.
