### ISSUE TITLE
Enable SD card manager

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#212]
Does not operate. Check all previous issues before enabling.

**Comment by borisbergman** [comment]
only launch of graf und meyer

**Comment by RamonZwaga** [comment]
Discuss with Michael if the existing tool 'DIRMP3' can be imported / if not: to be decided if we want to maintain SD card manager or if DIRMP3 as an external tool is sufficient (maybe partial graphical changes by PK to indicate it can be used for eXentro also.RZ: prefer last option.

**Comment by borisbergman** [comment]
DIR_MP3 is started when clicking sd card manager

**Comment by RamonZwaga** [comment]
Hi Michael,
Can you ensure that Boris gets the last DIR-MP3 so when a new Installer is compiled, this is also included.
Or is this button only referring to the .exe. of the tool at a certain location on the drive?
I think this would be best as Philippe was still making some changes, so we can always update that ourselves.

**Comment by hoherprotektor** [comment]
[DIR_MP3.zip](https://github.com/borisbergman/EscInstaller/files/1567290/DIR_MP3.zip)

**Comment by borisbergman** [comment]
done

**Comment by RamonZwaga** [comment]
Hi Boris,
1) Where on the C-drive is the GUI installed (after executing the setup file)? This must be a clear location (when following the link in 'start', we can not trace it). 
2) As we cannot check it; did you create a subfolder in which the MP3-DIR tool is stored? I assume you compiled this tool with the installer SW, so during setup it will be stored automatically? If we know where the folder for dir-mp3 is located, we can always to add a new version of this tool afterwards (so directly in the folder).

**Comment by RamonZwaga** [comment]
SD-card manager is now activated.
Issue closed; but for a possible future GUI update to read message names from text file, we may need to discuss time to implement for Boris first, than open an new issue
