### ISSUE TITLE
Create installation package

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#216]
Include peq library, #208

**Comment by RamonZwaga** [comment]
??

**Comment by borisbergman** [comment]
This is left till the end. I'll explain Michael how to build one.

**Comment by RamonZwaga** [comment]
Installing a new version should first remove the old version....
![image](https://user-images.githubusercontent.com/8523943/34265065-290cf800-e675-11e7-9196-9ca28ede42d4.png)

**Comment by borisbergman** [comment]
Should be working. If it doesn't, remove manually.

**Comment by RamonZwaga** [comment]
But did you change anything? Or did you only check if it was ok on your computer?
