### ISSUE TITLE
create save as button 

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#217]

**Comment by RamonZwaga** [comment]
If someone want to do a save (design V1) and continue with a V2 design, this is now not possible

**Comment by borisbergman** [comment]
Seems already working.

**Comment by hoherprotektor** [comment]
in the last version ist was there but greyed out. It must be available if and if not connected to the unit.

**Comment by borisbergman** [comment]
Please build the latest development version 13.8.3 to test this feature.

**Comment by hoherprotektor** [comment]
1. Its ok but the endings is set two times.  

![gui2](https://cloud.githubusercontent.com/assets/19922934/24491344/17904f48-1527-11e7-8a38-d98d9656d37f.JPG)
2. When creating an new file then the popup message appears that the file is not for the new version, but its made in this version.

**Comment by borisbergman** [comment]
I don't understand your second point, What exactly is this message box saying? When do you create a new file?

**Comment by hoherprotektor** [comment]
![gui3](https://cloud.githubusercontent.com/assets/19922934/24599198/58254b64-184f-11e7-869a-d609fd4ff6ba.JPG)

**Comment by hoherprotektor** [comment]
first upload without create a new file. then create one because you have to do. Sometimes the upper message appears then when you upload it. When you download this file again it also appears.

**Comment by hoherprotektor** [comment]
"Save as" still greyed out

**Comment by RamonZwaga** [comment]
Seen in new release, seems to work also :)
