### ISSUE TITLE
Customize mute music during power outage 

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#220]
Disable and enable music mute in menu.

**Comment by borisbergman** [comment]
A command has to be created no?

**Comment by hoherprotektor** [comment]
for the Protocol you mean?

**Comment by borisbergman** [comment]
Yes. Please put the command over here.

**Comment by hoherprotektor** [comment]
ok. do it today.

**Comment by borisbergman** [comment]
No command. Please provide one or close issue.

**Comment by hoherprotektor** [comment]
![grafik](https://cloud.githubusercontent.com/assets/19922934/24644844/de62eefe-1915-11e7-9667-8223ff6bfad4.png)

**Comment by hoherprotektor** [comment]
![grafik](https://cloud.githubusercontent.com/assets/19922934/24645008/b08dbb98-1916-11e7-8bee-27c9f9207f49.png)

**Comment by hoherprotektor** [comment]
![grafik](https://cloud.githubusercontent.com/assets/19922934/24645100/11113c6a-1917-11e7-89d1-2bc7cb1147fa.png)
