### ISSUE TITLE
Missmatch .esc file

### ISSUE THREAD

**Issue by hoherprotektor** [borisbergman/EscInstaller#224]
When you want to upload a file with saving a .esc file, software asks to save a new file. Thats ok. 
If you they yes, then the window pop up and says that there is a missmatch between those files and this new software version. This is strange

**Comment by borisbergman** [comment]
I cannot reproduce this. Please elaborate more and post a view pictures to describe what is going on.

**Comment by hoherprotektor** [comment]
![gui3](https://cloud.githubusercontent.com/assets/19922934/24598808/b123a24e-184d-11e7-81c1-76b0595da5f4.JPG)

**Comment by hoherprotektor** [comment]
When you upload a new data and download it. this message appears. But it was the same file made with the same version.

**Comment by borisbergman** [comment]
Fixed by removing message box. This feature was never requested.
