### ISSUE TITLE
Download failure 'sensitivity'

### ISSUE THREAD

**Issue by RamonZwaga** [borisbergman/EscInstaller#225]
When we perform a download of the design, the SW crashes at the 'sensitivity' point.
If we do a download without that sens., all seems ok, but: the design shows 12 channels while only 1 4x4 card is installed (is that due to the 'sens' values not received.

After that we only download 'sensitivity' and the values are downloaded, but the number of channels is still 12 (should be 4).

**Comment by borisbergman** [comment]
This has been tested with the emulator. Please provide feedback of esc when downloading sensitivity values for each of the three scenario's.

**Comment by RamonZwaga** [comment]
Which 3 scenario's?
1. we do a download with checkmarks set: SW crashes at the moment it starts to download Sensitivity.
2. checkmark only set at 'Sensitivity': download ok.
BUT: in both cases the number of installed 4x4 cards is not correct!

**Comment by borisbergman** [comment]
Not reproducable
