### ISSUE TITLE
Up/Download window

### ISSUE THREAD

**Issue by RamonZwaga** [borisbergman/EscInstaller#226]
Every time you open this window, the button 'start' should be visible sometimes it comes up with 'reset' at first, which is not ok.

Can we also have an indication when the up/download is finished? Now we only see progress bars and at some point (if the bars seem filled), one needs to decide if the up/download is ready....

**Comment by borisbergman** [comment]
This is already mentioned in #211. Please read everything carefully before opening new tickets. Extra indication will be out of scope for this project.
