### ISSUE TITLE
"+" Button to add slave

### ISSUE THREAD

**Issue by hoherprotektor** [borisbergman/EscInstaller#227]
We recognized that in the latest Version the "+" Button to add slaves is not working anymore

**Comment by hoherprotektor** [comment]
still greyed out
![plusslave](https://user-images.githubusercontent.com/19922934/33546313-fd72092a-d8e0-11e7-9c75-06f296717af3.JPG)

**Comment by borisbergman** [comment]
solved

**Comment by RamonZwaga** [comment]
OK
