### ISSUE TITLE
EQ- data transmission fail

### ISSUE THREAD

**Issue by mrgplusm** [borisbergman/EscInstaller#228]
Transferring of the EQ- data with the pre- built EQ works but if there is a change or addition of filters there is no change at the outputs from the ECU.
When checking we noticed that there  are different sized data blocks sent from the GUI even at the same commands.
At any time there are no more data sent by the GUI anymore, even "Install mode on" is displayed.

**Comment by mrgplusm** [comment]
Following filters aren't working:
-Notch
-LowShelf
-HighShelf

**Comment by RamonZwaga** [comment]
Hi Boris, can you also tell at which addresses you store the EQ data? Maybe we (ECU) check at a part of the addresses, so we miss data to update the EQ filters in the DSP.

**Comment by hoherprotektor** [comment]
![image](https://user-images.githubusercontent.com/19922934/31169837-4883044e-a8fa-11e7-8a52-218f71e46d8a.png)

Here are the functions for the filters which do not work.

**Comment by borisbergman** [comment]
Implemented shelf filters but untested. I still have to simulate those with matlab.

**Comment by borisbergman** [comment]
Fully implemented and tested

**Comment by RamonZwaga** [comment]
did you also include the notch filter? Above peaking filter we already have since the start, so is a bit misleading when look at the picture: notch is nr.3 (not peaking).

**Comment by hoherprotektor** [comment]
Highshelf: Filter should amplify the Signal higher then the Frequency chosen.  For lower frequency it should be 0dB not -XdB
![image](https://user-images.githubusercontent.com/19922934/33545232-bce87f54-d8dd-11e7-8ce2-48c0f31cca27.png)
but should be:
![eqhighshelf](https://user-images.githubusercontent.com/19922934/33545407-6a8cbaee-d8de-11e7-9323-d974f4f18eb9.JPG)

**Comment by hoherprotektor** [comment]
Lowshelf: Filter rises not high enough in the graphic
![eqlowshelf](https://user-images.githubusercontent.com/19922934/33545530-cca0a574-d8de-11e7-8dad-22dd86051a4c.JPG)

**Comment by RamonZwaga** [comment]
![image](https://user-images.githubusercontent.com/8523943/33549982-a5fb7b2a-d8ec-11e7-81a8-f9b21940c05d.png)
Highshelf filter as reference from Bose ControlSpace

![image](https://user-images.githubusercontent.com/8523943/33550015-bf31b8fc-d8ec-11e7-8241-5ddc86e8cf5e.png)
Lowshelf filter as reference from Bose ControlSpace

**Comment by RamonZwaga** [comment]
See below picture: I added 2 Low shelf filters and gave them both a boos (15dB), than I change the 2nd filter to a BW, but the values stayed (but greyed out); these should be set back to 0 as for a BW  (LW & Bessel) one cannot change boost/band/Q ...
![image](https://user-images.githubusercontent.com/8523943/33550163-374b8552-d8ed-11e7-8bc9-553c0b6892d4.png)

**Comment by hoherprotektor** [comment]
I also tried to measure the filters today.  What I discovered is that no EQ is working in the version 13.9.0.5. Also if i tried to upload the data the musik on  my inputs stoped. so no audio over the DSP. 
After that I wondered if I made a mistake. But after I tried it with the V 13.8.4. everthing but the shelf and notch filter is working fine.

**Comment by borisbergman** [comment]
Hmm strange. Do you mean if you upload an EQ there's no detectable sound at the output? What filters did you select?

**Comment by hoherprotektor** [comment]
normaly you can do it without uploading. But with upload also no reaction. Every filter. This was my test setup. I was connected to an slave 4 unit
![image](https://user-images.githubusercontent.com/19922934/33616870-774dfb34-d9de-11e7-9ebe-4bdace7623bd.png)

**Comment by RamonZwaga** [comment]
What is the status?

**Comment by borisbergman** [comment]
I've extensively tested the data and couldn't find any inconsistencies. Please tell me whats wrong.

**Comment by RamonZwaga** [comment]
V13.9.0.6: 12dB boost (entered), but a 6dB boost shown in Freq.curve. Did you check this?:
![image](https://user-images.githubusercontent.com/8523943/34214355-885810ca-e5a2-11e7-8fd6-bd9b0978868a.png)

V13.9.0.6: Negative boost not ok. Did you check this?:
![image](https://user-images.githubusercontent.com/8523943/34214418-b9adb2b0-e5a2-11e7-8867-746a10069af9.png)

When testing new filters (2 weeks ago), we connected an audio-source and amplifier+speaker to the controller; changed filters real time & uploaded new design with changed filters, but no audible change in the sound at all. ALL FILTERS seem not to work anymore.

**Comment by mrgplusm** [comment]
With FW 13.9.0.10 still no function of the EQ (tested with every filter), even when uploading the design.
Also an issue: when uploaded, the gains (input/output) are set automatically to -60db

**Comment by borisbergman** [comment]
![eq-check](https://user-images.githubusercontent.com/6067502/34315589-40f12ea6-e782-11e7-8510-2c27296a8d8f.png)
I checked the eq with the python emulator (can be found in my repositories) and everything seems to be okay. I also checked the parameters in sigma studio. What's expected comes out. The data is as specified, there's nothing else I can do.

**Comment by RamonZwaga** [comment]
I asked Michael to think where else this can go wrong. Is it correct that you directly write to the DSP eprom? Just in case: can you tell us to which addresses your write to?

**Comment by hoherprotektor** [comment]
It can be that something goes wrong. But you Boris can find out really easy I think. For me its not. I didn't not have really a debug possiblity. First step would be the step to campare the protocol for version v13.8.4 with version v13.9.0.10. There must be a difference in the protocol structure. the coeffs seems to be wright like you show us in sigma st. But like I said I think there must be something wrong in the protocolpart in the installer because  the firmware for the protocol didn't not change since the times of patrick. That's why I think something must gone wrong on you side Boris.  To be clear: No EQ can be setup or can be changed in the last and previous software. not only the notch or the shelf  filters.  I talk also with manfred today to see what we can do. But it is not so much I think.

**Comment by borisbergman** [comment]
Probably addresses weren't referenced in installer.
