### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by hoherprotektor** [borisbergman/EscInstaller#229]
We recoginized that on different computers we have the problem that the installer stopped working with the  "installer stopped working" message. This happens on many different computers in serveral situations. 

this kind:
![index](https://user-images.githubusercontent.com/19922934/31650379-50df120a-b317-11e7-981d-d0062d14d5b4.png)

**Comment by borisbergman** [comment]
Please elaborate "serveral situations".

**Comment by hoherprotektor** [comment]
we see if it improves in the new version. Problably it is solved yet

**Comment by borisbergman** [comment]
Can be reopened if still arises. Please be more specific so it can be reproduced and solved.
