### ISSUE TITLE
Other buttons with 'issues'

### ISSUE THREAD

**Issue by RamonZwaga** [borisbergman/EscInstaller#230]
![image](https://user-images.githubusercontent.com/8523943/33549017-7ad2f480-d8e9-11e7-8947-8d3ff67d1868.png)

Above: small change in name of button

![image](https://user-images.githubusercontent.com/8523943/33549063-9b0e2bd4-d8e9-11e7-8007-2aa180462c8b.png)

Above: 'close current project' is greyed out, like 'save as' and 'add new unit'
![image](https://user-images.githubusercontent.com/8523943/33549184-f3dd9132-d8e9-11e7-81ee-df1f4394c79a.png)

Above: 'calibration start' not possible, please remove button. Can we still activate the 'measurement settings' button in the config file? If yes: where is the application installed on the computer? In the 'start menu' now there is a folder 'Graf & Meyer' with a sub folder eXentro > following this link, only directs to a link. Where is all stored?

@ Michael: the 'music mute during 48V operation' is this already implemented in the protocol?

@ Boris: the default setting is wrong > text says 'music mute during 48Vdc operation', so it should be checked already. If someone want to continue playing music during 48Vdc operation it should be un-selected and following should appear:
![image](https://user-images.githubusercontent.com/8523943/33549541-3251cfc2-d8eb-11e7-8dff-e90f976583a0.png)
It seems conflicting operation / display of info regarding the state of this function

**Comment by RamonZwaga** [comment]
![image](https://user-images.githubusercontent.com/8523943/34080735-24fef37e-e343-11e7-8708-af4cae24af2d.png)
It seems we already have the code for this music mute function during 48V operation.
Default is: music OFF, (so byte 6 is 0x02), when music ON (during 48V operation is selected), byte 6 = 0x01. Please not the current wrong 'checkmark' next to this menu item! The Popup text is ok, but should onlu popup when you set this to yes (V)..

**Comment by borisbergman** [comment]
Toggled behavior of music mute. Newly created designs fill have this selected by default.

**Comment by RamonZwaga** [comment]
Seen in new release, seems to work also :)

Maybe a small one for the 'music mute during 48V' button...:
When opening a design (in which this function was not selected, so no checkmark) and I now select (activate) this function, the checkmark (V) is set (I assume '0x01' is send(?)) , but no message pops up which indicates 'music will not play during 48V mode'...: is that correct or did we (at Bose time) implement a popup message for that?

When de-selecting this option again, so we now allow music to be played during 48V mode (assuming 0x02 is send now (?)), this message pops up: 
![image](https://user-images.githubusercontent.com/8523943/34212003-2c541a32-e59b-11e7-8a80-172850a953bc.png)
This seems correct.
